cloudexpo/src/objects/Club__c.object
<CustomObject>
    <description>Object to represent individual clubs</description>
    <fields>
        <fullName>ClubID__c</fullName>
        <description>External eClubID for Club</description>
        <externalId>true</externalId>
        <label>ClubID</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Club</label>
    <nameField>
        <label>Club Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clubs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

cloudexpo/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Home_Club__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Home Club</label>
        <referenceTo>Club__c</referenceTo>
        <relationshipLabel>Contacts (Home Club)</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

cloudexpo/src/objects/Goal__c.object
<CustomObject>
    <fields>
        <fullName>Club__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Club</label>
        <referenceTo>Club__c</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GoalMonth__c</fullName>
        <label>GoalMonth</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GoalYear__c</fullName>
        <label>GoalYear</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PTGoal__c</fullName>
        <label>PTGoal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Goal</label>
    <nameField>
        <label>Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

cloudexpo/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Is_Trainer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Trainer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Trainer_Tier__c</fullName>
        <label>Trainer Tier</label>
        <picklist>
            <picklistValues>
                <fullName>Tier 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tier 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tier 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tier 3+</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tier 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Master</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advantage</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

cloudexpo/src/classes/TrainerGoalControllerTest.cls
/*
 * @author Debadyuti Sil
 * @Date   2 Jun 2014
 * @purpose Test Class  for TrainerGoalController
 */

@isTest
public class TrainerGoalControllerTest{
  
    public static testmethod void processTrainerGoalControllerTest(){
        //create club
        Club__c testClub = new Club__c(Name = '19th street', clubId__c =  '19th street');
        insert testClub;
        system.assert(testClub.id <> null);
        //create user
         Profile p = [select id from profile where  Name = 'System Administrator' limit 1];
        User testUser = new User(
            FirstName='User test',
            LastName='Test',
            Alias='Test123',
            Username='usertest123@equinox.com',
            email='user@bmi.com',
            CommunityNickname='usertest123',
            TimeZoneSidKey='America/Los_Angeles',
            localesidkey='en_US',
            profileId = p.Id,
            EmailEncodingKey='UTF-8',
            LanguageLocaleKey='en_US',
            trainer_tier__c = 'Tier 1',
            Is_trainer__c = true);
        insert testUser;
        system.assert(testUser.id <> null);

        //create Contact
        Contact testContact = new Contact(Home_Club__c = testClub.Id,User__c = testUser.Id,lastname='TestCon');
        insert testContact;
        system.assert(testContact.id <> null);
        
        Goal__c testCurrentMonthGoal = new Goal__c(PTGoal__c = 45,User__c=testUser.ID, GoalMonth__c=System.now().month(), GoalYear__c = system.now().year());
        insert  testCurrentMonthGoal;
        Goal__c testPreviousMonthGoal = new Goal__c(PTGoal__c = 40,User__c=testUser.ID, GoalMonth__c=System.now().month()-1, GoalYear__c = system.now().year());
        insert  testPreviousMonthGoal; 
        
        Test.startTest();
         
         ApexPages.StandardController sc = new ApexPages.StandardController(testContact);
         TrainerGoalController testcontroller = new TrainerGoalController(sc);
         Pagereference testPage = page.TrainerGoal;
         Test.setcurrentpage(testPage);
         testcontroller.selectClub = testClub.Id;
         testcontroller.selectedTier = 'Tier 1';
         testcontroller.processFilter();
         apexpages.currentPage().getparameters().put('trainerIdparam',testUser.Id);
         testcontroller.processSubmitSpecificTrainerGoal();
         testcontroller.next();
         testcontroller.last();
         testcontroller.previous();
         testcontroller.first();
         testcontroller.resetAll();
         testcontroller.submitAll();
         
        Test.stopTest();
        
    }
}